seed: 42
data: nyu_depth_v2
batch_size: 4
num_workers: 0
weight_decay: 1e-2
learning_rate: 1e-3
epochs: 50
num_outs: 3
source_dir: src
model_dir: models
architecture: resnet34
loss_func: MSELossFlat
train_metric: rmse
